// scripts/seed_forests.ts
// ─────────────────────────────────────────────────────────────────
// Korea Trekking Hub — 자연휴양림 시드 + 카카오 지오코딩
// 실행: npx tsx scripts/seed_forests.ts
//
// 필요 환경변수 (.env.local):
//   NEXT_PUBLIC_SUPABASE_URL          Supabase 프로젝트 URL
//   SUPABASE_SERVICE_ROLE_KEY         서비스 롤 키 (RLS bypass)
//   KAKAO_REST_API_KEY                카카오 REST API 키 (지오코딩용)
//
// 동작:
//   1) 185개 휴양림을 카카오 로컬 API로 지오코딩 (키워드 → 주소 fallback)
//   2) 좌표를 채워 Supabase forests 테이블에 upsert
//   3) 지오코딩 실패 건은 geocoded=false 로 적재 (지도에서 자동 제외)
//   4) 결과를 scripts/forests_geocoded.json 으로도 저장 (재현/검수용)
//
// 카카오 키워드 검색 일 30,000건 무료. 185건이라 1회 실행으로 충분.
// 재실행 시 이미 좌표가 있는 항목은 캐시(json)에서 재사용해 호출을 아낍니다.
// ─────────────────────────────────────────────────────────────────
import { createClient } from '@supabase/supabase-js';
import fs from 'node:fs';
import path from 'node:path';

const SUPABASE_URL = process.env.NEXT_PUBLIC_SUPABASE_URL!;
const SERVICE_KEY  = process.env.SUPABASE_SERVICE_ROLE_KEY!;
const KAKAO_KEY    = process.env.KAKAO_REST_API_KEY!;

if (!SUPABASE_URL || !SERVICE_KEY) {
  console.error('❌ NEXT_PUBLIC_SUPABASE_URL / SUPABASE_SERVICE_ROLE_KEY 가 필요합니다.');
  process.exit(1);
}
if (!KAKAO_KEY) {
  console.warn('⚠️  KAKAO_REST_API_KEY 가 없습니다. 좌표 없이 적재만 진행합니다 (지도 미표시).');
}

const supabase = createClient(SUPABASE_URL, SERVICE_KEY);

interface ForestSeed {
  id: string; name: string; category: '국립' | '공립' | '사립';
  region: string; sigungu: string; address: string;
  lat: number | null; lng: number | null; geocoded: boolean;
  has_room: boolean; has_camp: boolean; has_waitlist: boolean;
  fcfs_type: string; open_time: string;
  lottery_targets: string[]; priority_targets: string[];
  reservation_url: string; reservation_org: string; note: string;
}

// ── 185개 휴양림 마스터 데이터 (엑셀 출처) ──────────────────────────
const FORESTS: ForestSeed[] = [
  {"id": "nf-001", "name": "유명산 자연휴양림", "category": "국립", "region": "서울인천경기", "sigungu": "가평군", "address": "가평군 유명산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-002", "name": "아세안 자연휴양림", "category": "국립", "region": "서울인천경기", "sigungu": "양주시", "address": "양주시 아세안 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인"], "priority_targets": ["아세안"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-003", "name": "산음 자연휴양림", "category": "국립", "region": "서울인천경기", "sigungu": "양평군", "address": "양평군 산음 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-004", "name": "중미산 자연휴양림", "category": "국립", "region": "서울인천경기", "sigungu": "양평군", "address": "양평군 중미산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-005", "name": "무의도 자연휴양림", "category": "국립", "region": "서울인천경기", "sigungu": "중구", "address": "중구 무의도 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인"], "priority_targets": [], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-006", "name": "운악산 자연휴양림", "category": "국립", "region": "서울인천경기", "sigungu": "포천시", "address": "포천시 운악산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-007", "name": "대관령 자연휴양림", "category": "국립", "region": "강원", "sigungu": "강릉시", "address": "강릉시 대관령 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-008", "name": "진부령 자연휴양림", "category": "국립", "region": "강원", "sigungu": "고성군", "address": "고성군 진부령 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인"], "priority_targets": [], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-009", "name": "검봉산 자연휴양림", "category": "국립", "region": "강원", "sigungu": "삼척시", "address": "삼척시 검봉산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "실버"], "priority_targets": [], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-010", "name": "미천골 자연휴양림", "category": "국립", "region": "강원", "sigungu": "양양군", "address": "양양군 미천골 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["아세안", "바우처", "지역주민", "기타"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-011", "name": "백운산 자연휴양림", "category": "국립", "region": "강원", "sigungu": "원주시", "address": "원주시 백운산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-012", "name": "방태산 자연휴양림", "category": "국립", "region": "강원", "sigungu": "인제군", "address": "인제군 방태산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "실버"], "priority_targets": [], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-013", "name": "용대 자연휴양림", "category": "국립", "region": "강원", "sigungu": "인제군", "address": "인제군 용대 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": [], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-014", "name": "가리왕산 자연휴양림", "category": "국립", "region": "강원", "sigungu": "정선군", "address": "정선군 가리왕산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-015", "name": "복주산 자연휴양림", "category": "국립", "region": "강원", "sigungu": "철원군", "address": "철원군 복주산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-016", "name": "용화산 자연휴양림", "category": "국립", "region": "강원", "sigungu": "춘천시", "address": "춘천시 용화산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": [], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-017", "name": "두타산 자연휴양림(평창)", "category": "국립", "region": "강원", "sigungu": "평창군", "address": "평창군 두타산 자연휴양림(평창)", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-018", "name": "삼봉 자연휴양림", "category": "국립", "region": "강원", "sigungu": "홍천군", "address": "홍천군 삼봉 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-019", "name": "화천숲속 야영장", "category": "국립", "region": "강원", "sigungu": "화천군", "address": "화천군 화천숲속 야영장", "lat": null, "lng": null, "geocoded": false, "has_room": false, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "다자녀"], "priority_targets": [], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-020", "name": "청태산 자연휴양림", "category": "국립", "region": "강원", "sigungu": "횡성군", "address": "횡성군 청태산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-021", "name": "황정산 자연휴양림", "category": "국립", "region": "충북", "sigungu": "단양군", "address": "단양군 황정산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-022", "name": "속리산 말티재자연휴양림", "category": "국립", "region": "충북", "sigungu": "보은군", "address": "보은군 속리산 말티재자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-023", "name": "상당산성 자연휴양림", "category": "국립", "region": "충북", "sigungu": "청주시 청원구", "address": "청주시 청원구 상당산성 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-024", "name": "금산 자연휴양림", "category": "국립", "region": "대전충남", "sigungu": "금산군", "address": "금산군 금산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-025", "name": "오서산 자연휴양림", "category": "국립", "region": "대전충남", "sigungu": "보령시", "address": "보령시 오서산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-026", "name": "용현 자연휴양림", "category": "국립", "region": "대전충남", "sigungu": "서산시", "address": "서산시 용현 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-027", "name": "희리산 자연휴양림", "category": "국립", "region": "대전충남", "sigungu": "서천군", "address": "서천군 희리산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-028", "name": "신시도자연휴양림", "category": "국립", "region": "전북", "sigungu": "군산시", "address": "군산시 신시도자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["아세안", "바우처", "지역주민", "기타"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-029", "name": "덕유산 자연휴양림", "category": "국립", "region": "전북", "sigungu": "무주군", "address": "무주군 덕유산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-030", "name": "변산 자연휴양림", "category": "국립", "region": "전북", "sigungu": "부안군", "address": "부안군 변산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-031", "name": "회문산 자연휴양림", "category": "국립", "region": "전북", "sigungu": "순창군", "address": "순창군 회문산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-032", "name": "운장산 자연휴양림", "category": "국립", "region": "전북", "sigungu": "진안군", "address": "진안군 운장산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-033", "name": "낙안민속 자연휴양림", "category": "국립", "region": "광주전남", "sigungu": "순천시", "address": "순천시 낙안민속 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-034", "name": "방장산 자연휴양림", "category": "국립", "region": "광주전남", "sigungu": "장성군", "address": "장성군 방장산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-035", "name": "천관산 자연휴양림", "category": "국립", "region": "광주전남", "sigungu": "장흥군", "address": "장흥군 천관산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": [], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-036", "name": "진도 자연휴양림", "category": "국립", "region": "광주전남", "sigungu": "진도군", "address": "진도군 진도 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-037", "name": "김천숲속야영장", "category": "국립", "region": "대구경북", "sigungu": "김천시", "address": "김천시 김천숲속야영장", "lat": null, "lng": null, "geocoded": false, "has_room": false, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기"], "priority_targets": [], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-038", "name": "대야산 자연휴양림", "category": "국립", "region": "대구경북", "sigungu": "문경시", "address": "문경시 대야산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-039", "name": "청옥산 자연휴양림", "category": "국립", "region": "대구경북", "sigungu": "봉화군", "address": "봉화군 청옥산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀"], "priority_targets": [], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-040", "name": "칠보산 자연휴양림", "category": "국립", "region": "대구경북", "sigungu": "영덕군", "address": "영덕군 칠보산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처", "기타"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-041", "name": "검마산 자연휴양림", "category": "국립", "region": "대구경북", "sigungu": "영양군", "address": "영양군 검마산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인"], "priority_targets": [], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-042", "name": "통고산 자연휴양림", "category": "국립", "region": "대구경북", "sigungu": "울진군", "address": "울진군 통고산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-043", "name": "운문산 자연휴양림", "category": "국립", "region": "대구경북", "sigungu": "청도군", "address": "청도군 운문산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-044", "name": "달음산 자연휴양림", "category": "국립", "region": "부산경남", "sigungu": "기장군", "address": "기장군 달음산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀"], "priority_targets": [], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-045", "name": "용지봉 자연휴양림", "category": "국립", "region": "부산경남", "sigungu": "김해시", "address": "김해시 용지봉 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀"], "priority_targets": [], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-046", "name": "남해편백 자연휴양림", "category": "국립", "region": "부산경남", "sigungu": "남해군", "address": "남해군 남해편백 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처", "기타"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-047", "name": "신불산 자연휴양림", "category": "국립", "region": "부산경남", "sigungu": "울주군", "address": "울주군 신불산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": [], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "nf-048", "name": "지리산 자연휴양림", "category": "국립", "region": "부산경남", "sigungu": "함양군", "address": "함양군 지리산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "장애인", "다자녀", "실버"], "priority_targets": ["바우처"], "reservation_url": "https://www.huyang.go.kr", "reservation_org": "숲나들e (국립자연휴양림관리소)", "note": ""},
  {"id": "pf-049", "name": "강씨봉자연휴양림", "category": "공립", "region": "서울인천경기", "sigungu": "가평군", "address": "가평군 강씨봉자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": ["월"], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-050", "name": "칼봉산자연휴양림", "category": "공립", "region": "서울인천경기", "sigungu": "가평군", "address": "가평군 칼봉산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 10일 16시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-051", "name": "석모도자연휴양림", "category": "공립", "region": "서울인천경기", "sigungu": "강화군", "address": "강화군 석모도자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-052", "name": "축령산자연휴양림", "category": "공립", "region": "서울인천경기", "sigungu": "남양주시", "address": "남양주시 축령산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": ["월"], "priority_targets": ["바우처", "지역주민", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-053", "name": "수락산 동막골 자연휴양림", "category": "공립", "region": "서울인천경기", "sigungu": "노원구", "address": "노원구 수락산 동막골 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 10일 14시 오픈", "lottery_targets": [], "priority_targets": ["지역주민", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-054", "name": "동두천자연휴양림", "category": "공립", "region": "서울인천경기", "sigungu": "동두천시", "address": "동두천시 동두천자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 화요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-055", "name": "서운산자연휴양림", "category": "공립", "region": "서울인천경기", "sigungu": "안성시", "address": "안성시 서운산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 3일 14시 오픈", "lottery_targets": ["월", "지역주민"], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-056", "name": "신암저수지 숲속야영장", "category": "공립", "region": "서울인천경기", "sigungu": "양주시", "address": "양주시 신암저수지 숲속야영장", "lat": null, "lng": null, "geocoded": false, "has_room": false, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 10시 오픈", "lottery_targets": [], "priority_targets": ["지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-057", "name": "양평 백운봉 자연휴양림", "category": "공립", "region": "서울인천경기", "sigungu": "양평군", "address": "양평군 양평 백운봉 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "4주", "open_time": "매주 수요일 10시 오픈", "lottery_targets": ["성수기"], "priority_targets": ["지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-058", "name": "양평쉬자파크", "category": "공립", "region": "서울인천경기", "sigungu": "양평군", "address": "양평군 양평쉬자파크", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "4주", "open_time": "매주 수요일 10시 오픈", "lottery_targets": [], "priority_targets": ["지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-059", "name": "고대산 자연휴양림", "category": "공립", "region": "서울인천경기", "sigungu": "연천군", "address": "연천군 고대산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["월", "지역주민"], "priority_targets": ["바우처", "지역주민", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-060", "name": "덕적도 자연휴양림", "category": "공립", "region": "서울인천경기", "sigungu": "옹진군", "address": "옹진군 덕적도 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": false, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": ["장애인"], "priority_targets": [], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-061", "name": "용인자연휴양림", "category": "공립", "region": "서울인천경기", "sigungu": "용인시 처인구", "address": "용인시 처인구 용인자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 10일 13시 오픈", "lottery_targets": ["월", "다자녀", "지역주민"], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-062", "name": "의왕바라산자연휴양림", "category": "공립", "region": "서울인천경기", "sigungu": "의왕시", "address": "의왕시 의왕바라산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 11일 09시 오픈", "lottery_targets": ["월", "지역주민"], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-063", "name": "천보산 자연휴양림", "category": "공립", "region": "서울인천경기", "sigungu": "포천시", "address": "포천시 천보산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-064", "name": "무봉산 자연휴양림", "category": "공립", "region": "서울인천경기", "sigungu": "화성시 동탄구", "address": "화성시 동탄구 무봉산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-065", "name": "임해자연휴양림", "category": "공립", "region": "강원", "sigungu": "강릉시", "address": "강릉시 임해자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-066", "name": "광치자연휴양림", "category": "공립", "region": "강원", "sigungu": "양구군", "address": "양구군 광치자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-067", "name": "송이밸리자연휴양림", "category": "공립", "region": "강원", "sigungu": "양양군", "address": "양양군 송이밸리자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-068", "name": "영월망경대산자연휴양림", "category": "공립", "region": "강원", "sigungu": "영월군", "address": "영월군 영월망경대산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-069", "name": "치악산자연휴양림", "category": "공립", "region": "강원", "sigungu": "원주시", "address": "원주시 치악산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-070", "name": "갯골자연휴양림", "category": "공립", "region": "강원", "sigungu": "인제군", "address": "인제군 갯골자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 4일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-071", "name": "하추자연휴양림", "category": "공립", "region": "강원", "sigungu": "인제군", "address": "인제군 하추자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 4일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-072", "name": "철원 두루웰 숲속문화촌", "category": "공립", "region": "강원", "sigungu": "철원군", "address": "철원군 철원 두루웰 숲속문화촌", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-073", "name": "강원숲체험장", "category": "공립", "region": "강원", "sigungu": "춘천시", "address": "춘천시 강원숲체험장", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-074", "name": "집다리골자연휴양림", "category": "공립", "region": "강원", "sigungu": "춘천시", "address": "춘천시 집다리골자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-075", "name": "춘천숲자연휴양림", "category": "공립", "region": "강원", "sigungu": "춘천시", "address": "춘천시 춘천숲자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "2주", "open_time": "매주 수요일 일요일 14시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-076", "name": "태백고원자연휴양림", "category": "공립", "region": "강원", "sigungu": "태백시", "address": "태백시 태백고원자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-077", "name": "평창자연휴양림", "category": "공립", "region": "강원", "sigungu": "평창군", "address": "평창군 평창자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-078", "name": "가리산 자연휴양림", "category": "공립", "region": "강원", "sigungu": "홍천군", "address": "홍천군 가리산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-079", "name": "성불산자연휴양림", "category": "공립", "region": "충북", "sigungu": "괴산군", "address": "괴산군 성불산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 5일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-080", "name": "조령산 자연휴양림", "category": "공립", "region": "충북", "sigungu": "괴산군", "address": "괴산군 조령산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["다자녀"], "priority_targets": ["바우처", "지역주민", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-081", "name": "소백산자연휴양림", "category": "공립", "region": "충북", "sigungu": "단양군", "address": "단양군 소백산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-082", "name": "소선암자연휴양림", "category": "공립", "region": "충북", "sigungu": "단양군", "address": "단양군 소선암자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-083", "name": "속리산숲체험휴양마을", "category": "공립", "region": "충북", "sigungu": "보은군", "address": "보은군 속리산숲체험휴양마을", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": [], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-084", "name": "충북알프스자연휴양림", "category": "공립", "region": "충북", "sigungu": "보은군", "address": "보은군 충북알프스자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-085", "name": "민주지산자연휴양림", "category": "공립", "region": "충북", "sigungu": "영동군", "address": "영동군 민주지산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-086", "name": "장령산자연휴양림", "category": "공립", "region": "충북", "sigungu": "옥천군", "address": "옥천군 장령산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-087", "name": "백야자연휴양림", "category": "공립", "region": "충북", "sigungu": "음성군", "address": "음성군 백야자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 10시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-088", "name": "수레의산자연휴양림", "category": "공립", "region": "충북", "sigungu": "음성군", "address": "음성군 수레의산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 10시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-089", "name": "박달재자연휴양림", "category": "공립", "region": "충북", "sigungu": "제천시", "address": "제천시 박달재자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-090", "name": "옥전자연휴양림", "category": "공립", "region": "충북", "sigungu": "제천시", "address": "제천시 옥전자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-091", "name": "좌구산휴양랜드", "category": "공립", "region": "충북", "sigungu": "증평군", "address": "증평군 좌구산휴양랜드", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-092", "name": "생거진천자연휴양림", "category": "공립", "region": "충북", "sigungu": "진천군", "address": "진천군 생거진천자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 13시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-093", "name": "미원별빛자연휴양림", "category": "공립", "region": "충북", "sigungu": "청주시 상당구", "address": "청주시 상당구 미원별빛자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 5일 10시 오픈", "lottery_targets": ["월"], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-094", "name": "옥화자연휴양림", "category": "공립", "region": "충북", "sigungu": "청주시 상당구", "address": "청주시 상당구 옥화자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 5일 10시 오픈", "lottery_targets": ["주말"], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-095", "name": "계명산자연휴양림", "category": "공립", "region": "충북", "sigungu": "충주시", "address": "충주시 계명산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 3일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-096", "name": "문성자연휴양림", "category": "공립", "region": "충북", "sigungu": "충주시", "address": "충주시 문성자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 3일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-097", "name": "봉황자연휴양림", "category": "공립", "region": "충북", "sigungu": "충주시", "address": "충주시 봉황자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 3일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-098", "name": "공주산림휴양마을", "category": "공립", "region": "대전충남", "sigungu": "공주시", "address": "공주시 공주산림휴양마을", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-099", "name": "금산산림문화타운(남이자연휴양림)", "category": "공립", "region": "대전충남", "sigungu": "금산군", "address": "금산군 금산산림문화타운(남이자연휴양림)", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-100", "name": "양촌자연휴양림", "category": "공립", "region": "대전충남", "sigungu": "논산시", "address": "논산시 양촌자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "5주", "open_time": "매주 수요일 10시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-101", "name": "만인산자연휴양림", "category": "공립", "region": "대전충남", "sigungu": "동구", "address": "동구 만인산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-102", "name": "성주산자연휴양림", "category": "공립", "region": "대전충남", "sigungu": "보령시", "address": "보령시 성주산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-103", "name": "원산도자연휴양림", "category": "공립", "region": "대전충남", "sigungu": "보령시", "address": "보령시 원산도자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 6일 09시 오픈", "lottery_targets": ["월"], "priority_targets": [], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-104", "name": "만수산자연휴양림", "category": "공립", "region": "대전충남", "sigungu": "부여군", "address": "부여군 만수산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-105", "name": "장태산자연휴양림", "category": "공립", "region": "대전충남", "sigungu": "서구", "address": "서구 장태산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-106", "name": "영인산 자연휴양림", "category": "공립", "region": "대전충남", "sigungu": "아산시", "address": "아산시 영인산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-107", "name": "봉수산자연휴양림", "category": "공립", "region": "대전충남", "sigungu": "예산군", "address": "예산군 봉수산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-108", "name": "태학산자연휴양림", "category": "공립", "region": "대전충남", "sigungu": "천안시 동남구", "address": "천안시 동남구 태학산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "성수기", "지역주민"], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-109", "name": "칠갑산자연휴양림", "category": "공립", "region": "대전충남", "sigungu": "청양군", "address": "청양군 칠갑산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-110", "name": "안면도자연휴양림", "category": "공립", "region": "대전충남", "sigungu": "태안군", "address": "태안군 안면도자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 6일 09시 오픈", "lottery_targets": ["월"], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-111", "name": "용봉산자연휴양림", "category": "공립", "region": "대전충남", "sigungu": "홍성군", "address": "홍성군 용봉산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-112", "name": "김제 선암자연휴양림", "category": "공립", "region": "전북", "sigungu": "김제시", "address": "김제시 김제 선암자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-113", "name": "무주향로산자연휴양림", "category": "공립", "region": "전북", "sigungu": "무주군", "address": "무주군 무주향로산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": false, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-114", "name": "고산자연휴양림", "category": "공립", "region": "전북", "sigungu": "완주군", "address": "완주군 고산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "4주", "open_time": "매주 수요일 월요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-115", "name": "성수산왕의숲자연휴양림", "category": "공립", "region": "전북", "sigungu": "임실군", "address": "임실군 성수산왕의숲자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 화요일 09시 오픈", "lottery_targets": [], "priority_targets": ["지역주민", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-116", "name": "방화동자연휴양림", "category": "공립", "region": "전북", "sigungu": "장수군", "address": "장수군 방화동자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "4주", "open_time": "매주 수요일 월요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-117", "name": "와룡자연휴양림", "category": "공립", "region": "전북", "sigungu": "장수군", "address": "장수군 와룡자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "4주", "open_time": "매주 수요일 월요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-118", "name": "내장산자연휴양림", "category": "공립", "region": "전북", "sigungu": "정읍시", "address": "정읍시 내장산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["지역주민", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-119", "name": "데미샘자연휴양림", "category": "공립", "region": "전북", "sigungu": "진안군", "address": "진안군 데미샘자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": ["월", "성수기"], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-120", "name": "주작산자연휴양림", "category": "공립", "region": "광주전남", "sigungu": "강진군", "address": "강진군 주작산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 10시 오픈", "lottery_targets": [], "priority_targets": ["아세안", "바우처", "지역주민", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-121", "name": "팔영산자연휴양림", "category": "공립", "region": "광주전남", "sigungu": "고흥군", "address": "고흥군 팔영산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-122", "name": "광양백운산자연휴양림", "category": "공립", "region": "광주전남", "sigungu": "광양시", "address": "광양시 광양백운산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["지역주민"], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-123", "name": "산수유자연휴양림", "category": "공립", "region": "광주전남", "sigungu": "구례군", "address": "구례군 산수유자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 화요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-124", "name": "제암산자연휴양림", "category": "공립", "region": "광주전남", "sigungu": "보성군", "address": "보성군 제암산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "3주", "open_time": "매주 수요일 10시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-125", "name": "순천자연휴양림", "category": "공립", "region": "광주전남", "sigungu": "순천시", "address": "순천시 순천자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-126", "name": "여수봉황산자연휴양림", "category": "공립", "region": "광주전남", "sigungu": "여수시", "address": "여수시 여수봉황산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-127", "name": "기찬자연휴양림", "category": "공립", "region": "광주전남", "sigungu": "영암군", "address": "영암군 기찬자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": [], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-128", "name": "전라남도 완도자연휴양림", "category": "공립", "region": "광주전남", "sigungu": "완도군", "address": "완도군 전라남도 완도자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-129", "name": "흑석산자연휴양림", "category": "공립", "region": "광주전남", "sigungu": "해남군", "address": "해남군 흑석산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-130", "name": "백아산자연휴양림", "category": "공립", "region": "광주전남", "sigungu": "화순군", "address": "화순군 백아산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-131", "name": "한천자연휴양림", "category": "공립", "region": "광주전남", "sigungu": "화순군", "address": "화순군 한천자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-132", "name": "토함산자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "경주시", "address": "경주시 토함산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-133", "name": "미숭산자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "고령군", "address": "고령군 미숭산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-134", "name": "옥성자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "구미시", "address": "구미시 옥성자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-135", "name": "군위장곡자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "군위군", "address": "군위군 군위장곡자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-136", "name": "수도산자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "김천시", "address": "김천시 수도산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": ["주말", "성수기"], "priority_targets": ["바우처", "지역주민", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-137", "name": "비슬산자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "달성군", "address": "달성군 비슬산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-138", "name": "화원자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "달성군", "address": "달성군 화원자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-139", "name": "문수산자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "봉화군", "address": "봉화군 문수산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "5주", "open_time": "매주 수요일 화요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-140", "name": "성주봉자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "상주시", "address": "상주시 성주봉자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-141", "name": "독용산성자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "성주군", "address": "성주군 독용산성자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-142", "name": "안동호반자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "안동시", "address": "안동시 안동호반자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 10시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-143", "name": "영양에코둥지", "category": "공립", "region": "대구경북", "sigungu": "영양군", "address": "영양군 영양에코둥지", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 5일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-144", "name": "보현산자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "영천시", "address": "영천시 보현산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-145", "name": "운주산승마자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "영천시", "address": "영천시 운주산승마자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 13시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-146", "name": "구수곡자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "울진군", "address": "울진군 구수곡자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-147", "name": "금봉자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "의성군", "address": "의성군 금봉자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-148", "name": "청도자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "청도군", "address": "청도군 청도자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-149", "name": "청송자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "청송군", "address": "청송군 청송자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-150", "name": "송정자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "칠곡군", "address": "칠곡군 송정자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-151", "name": "팔공산금화자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "칠곡군", "address": "칠곡군 팔공산금화자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 10시 오픈", "lottery_targets": [], "priority_targets": ["아세안", "바우처", "지역주민", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-152", "name": "비학산자연휴양림", "category": "공립", "region": "대구경북", "sigungu": "포항시 북구", "address": "포항시 북구 비학산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-153", "name": "거제자연휴양림", "category": "공립", "region": "부산경남", "sigungu": "거제시", "address": "거제시 거제자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-154", "name": "거창산림레포츠파크", "category": "공립", "region": "부산경남", "sigungu": "거창군", "address": "거창군 거창산림레포츠파크", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["지역주민"], "priority_targets": [], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-155", "name": "거창항노화힐링랜드", "category": "공립", "region": "부산경남", "sigungu": "거창군", "address": "거창군 거창항노화힐링랜드", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "5주", "open_time": "매주 수요일 월요일 14시 오픈", "lottery_targets": [], "priority_targets": [], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-156", "name": "금원산자연휴양림", "category": "공립", "region": "부산경남", "sigungu": "거창군", "address": "거창군 금원산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-157", "name": "갈모봉 자연휴양림", "category": "공립", "region": "부산경남", "sigungu": "고성군", "address": "고성군 갈모봉 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": [], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-158", "name": "밀양 도래재자연휴양림", "category": "공립", "region": "부산경남", "sigungu": "밀양시", "address": "밀양시 밀양 도래재자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": ["장애인"], "priority_targets": ["지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-159", "name": "사천 케이블카 자연휴양림", "category": "공립", "region": "부산경남", "sigungu": "사천시", "address": "사천시 사천 케이블카 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["장애인"], "priority_targets": ["기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-160", "name": "산청한방자연휴양림", "category": "공립", "region": "부산경남", "sigungu": "산청군", "address": "산청군 산청한방자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-161", "name": "대운산자연휴양림", "category": "공립", "region": "부산경남", "sigungu": "양산시", "address": "양산시 대운산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["지역주민"], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-162", "name": "자굴산 자연휴양림", "category": "공립", "region": "부산경남", "sigungu": "의령군", "address": "의령군 자굴산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "4주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-163", "name": "진주 월아산 자연휴양림", "category": "공립", "region": "부산경남", "sigungu": "진주시", "address": "진주시 진주 월아산 자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-164", "name": "화왕산자연휴양림", "category": "공립", "region": "부산경남", "sigungu": "창녕군", "address": "창녕군 화왕산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-165", "name": "구재봉자연휴양림", "category": "공립", "region": "부산경남", "sigungu": "하동군", "address": "하동군 구재봉자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "4주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-166", "name": "하동편백자연휴양림", "category": "공립", "region": "부산경남", "sigungu": "하동군", "address": "하동군 하동편백자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "4주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-167", "name": "대봉산자연휴양림", "category": "공립", "region": "부산경남", "sigungu": "함양군", "address": "함양군 대봉산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "3주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-168", "name": "대봉캠핑랜드", "category": "공립", "region": "부산경남", "sigungu": "함양군", "address": "함양군 대봉캠핑랜드", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "4주", "open_time": "매주 수요일 월요일 10시 오픈", "lottery_targets": [], "priority_targets": ["지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-169", "name": "산삼자연휴양림", "category": "공립", "region": "부산경남", "sigungu": "함양군", "address": "함양군 산삼자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "3주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-170", "name": "용추자연휴양림", "category": "공립", "region": "부산경남", "sigungu": "함양군", "address": "함양군 용추자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "3주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처", "지역주민", "기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-171", "name": "오도산자연휴양림", "category": "공립", "region": "부산경남", "sigungu": "합천군", "address": "합천군 오도산자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": ["월"], "priority_targets": ["바우처", "지역주민"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-172", "name": "붉은오름자연휴양림", "category": "공립", "region": "제주", "sigungu": "서귀포시", "address": "서귀포시 붉은오름자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-173", "name": "서귀포자연휴양림", "category": "공립", "region": "제주", "sigungu": "서귀포시", "address": "서귀포시 서귀포자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["다자녀"], "priority_targets": ["기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-174", "name": "교래자연휴양림", "category": "공립", "region": "제주", "sigungu": "제주시", "address": "제주시 교래자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": ["바우처"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "pf-175", "name": "제주절물자연휴양림", "category": "공립", "region": "제주", "sigungu": "제주시", "address": "제주시 제주절물자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["다자녀"], "priority_targets": ["기타"], "reservation_url": "https://www.foresttrip.go.kr", "reservation_org": "숲나들e / 지자체 예약시스템", "note": ""},
  {"id": "rf-176", "name": "청평자연휴양림", "category": "사립", "region": "서울인천경기", "sigungu": "가평군", "address": "가평군 청평자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 00시 오픈", "lottery_targets": [], "priority_targets": [], "reservation_url": "", "reservation_org": "개별 휴양림 홈페이지", "note": ""},
  {"id": "rf-177", "name": "강화자연휴양림", "category": "사립", "region": "서울인천경기", "sigungu": "강화군", "address": "강화군 강화자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": [], "reservation_url": "", "reservation_org": "개별 휴양림 홈페이지", "note": ""},
  {"id": "rf-178", "name": "양평설매재자연휴양림", "category": "사립", "region": "서울인천경기", "sigungu": "양평군", "address": "양평군 양평설매재자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "익월말", "open_time": "매월 1일 09시 오픈", "lottery_targets": [], "priority_targets": [], "reservation_url": "", "reservation_org": "개별 휴양림 홈페이지", "note": ""},
  {"id": "rf-179", "name": "삼척활기자연휴양림", "category": "사립", "region": "강원", "sigungu": "삼척시", "address": "삼척시 삼척활기자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "8주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": [], "reservation_url": "", "reservation_org": "개별 휴양림 홈페이지", "note": ""},
  {"id": "rf-180", "name": "피노키오자연휴양림", "category": "사립", "region": "강원", "sigungu": "원주시", "address": "원주시 피노키오자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": [], "reservation_url": "", "reservation_org": "개별 휴양림 홈페이지", "note": ""},
  {"id": "rf-181", "name": "횡성자연휴양림", "category": "사립", "region": "강원", "sigungu": "횡성군", "address": "횡성군 횡성자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": [], "reservation_url": "", "reservation_org": "개별 휴양림 홈페이지", "note": ""},
  {"id": "rf-182", "name": "남원자연휴양림", "category": "사립", "region": "전북", "sigungu": "남원시", "address": "남원시 남원자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": [], "reservation_url": "", "reservation_org": "개별 휴양림 홈페이지", "note": ""},
  {"id": "rf-183", "name": "무등산편백자연휴양림", "category": "사립", "region": "광주전남", "sigungu": "화순군", "address": "화순군 무등산편백자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": ["주말", "월", "성수기", "장애인", "다자녀", "실버", "지역주민"], "priority_targets": [], "reservation_url": "", "reservation_org": "개별 휴양림 홈페이지", "note": ""},
  {"id": "rf-184", "name": "학가산우래자연휴양림", "category": "사립", "region": "대구경북", "sigungu": "예천군", "address": "예천군 학가산우래자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": true, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": [], "reservation_url": "", "reservation_org": "개별 휴양림 홈페이지", "note": ""},
  {"id": "rf-185", "name": "덕원자연휴양림", "category": "사립", "region": "부산경남", "sigungu": "하동군", "address": "하동군 덕원자연휴양림", "lat": null, "lng": null, "geocoded": false, "has_room": true, "has_camp": false, "has_waitlist": true, "fcfs_type": "6주", "open_time": "매주 수요일 09시 오픈", "lottery_targets": [], "priority_targets": [], "reservation_url": "", "reservation_org": "개별 휴양림 홈페이지", "note": ""}];

// ── 카카오 로컬 API 지오코딩 ────────────────────────────────────────
const CACHE_PATH = path.join(process.cwd(), 'scripts', 'forests_geocoded.json');

async function kakaoKeyword(query: string): Promise<{ lat: number; lng: number } | null> {
  const url = `https://dapi.kakao.com/v2/local/search/keyword.json?query=${encodeURIComponent(query)}&size=1`;
  const res = await fetch(url, { headers: { Authorization: `KakaoAK ${KAKAO_KEY}` } });
  if (!res.ok) return null;
  const json = await res.json();
  const doc = json.documents?.[0];
  if (!doc) return null;
  // 카카오: x=경도(lng), y=위도(lat)
  return { lat: parseFloat(doc.y), lng: parseFloat(doc.x) };
}

async function kakaoAddress(query: string): Promise<{ lat: number; lng: number } | null> {
  const url = `https://dapi.kakao.com/v2/local/search/address.json?query=${encodeURIComponent(query)}&size=1`;
  const res = await fetch(url, { headers: { Authorization: `KakaoAK ${KAKAO_KEY}` } });
  if (!res.ok) return null;
  const json = await res.json();
  const doc = json.documents?.[0];
  if (!doc) return null;
  return { lat: parseFloat(doc.y), lng: parseFloat(doc.x) };
}

async function geocode(f: ForestSeed): Promise<{ lat: number; lng: number } | null> {
  // 1순위: 휴양림명 키워드 (가장 정확)  2순위: 시군 + 이름  3순위: 시군 주소
  const tries = [f.name, `${f.sigungu} ${f.name}`, f.address];
  for (const q of tries) {
    const hit = await kakaoKeyword(q);
    if (hit) return hit;
    await sleep(120); // rate-limit 여유
  }
  const addr = await kakaoAddress(f.sigungu);
  return addr;
}

const sleep = (ms: number) => new Promise((r) => setTimeout(r, ms));

async function run() {
  // 캐시 로드 (재실행 시 호출 절약)
  let cache: Record<string, { lat: number; lng: number }> = {};
  if (fs.existsSync(CACHE_PATH)) {
    try { cache = JSON.parse(fs.readFileSync(CACHE_PATH, 'utf8')); } catch {}
  }

  let ok = 0, fail = 0, cached = 0;
  for (const f of FORESTS) {
    if (cache[f.id]) {
      f.lat = cache[f.id].lat; f.lng = cache[f.id].lng; f.geocoded = true; cached++;
      continue;
    }
    if (!KAKAO_KEY) { fail++; continue; }
    const hit = await geocode(f);
    if (hit) {
      f.lat = hit.lat; f.lng = hit.lng; f.geocoded = true;
      cache[f.id] = hit; ok++;
      process.stdout.write(`✅ ${f.name} (${hit.lat.toFixed(4)}, ${hit.lng.toFixed(4)})\n`);
    } else {
      f.geocoded = false; fail++;
      process.stdout.write(`⚠️  좌표 실패: ${f.name} [${f.sigungu}]\n`);
    }
    await sleep(120);
  }

  // 캐시 저장
  fs.writeFileSync(CACHE_PATH, JSON.stringify(cache, null, 1), 'utf8');
  console.log(`\n📍 지오코딩 결과 — 신규 ${ok} / 캐시 ${cached} / 실패 ${fail}`);

  // Supabase upsert (배치)
  console.log('🌱 forests 테이블 적재 중...');
  const chunkSize = 100;
  for (let i = 0; i < FORESTS.length; i += chunkSize) {
    const chunk = FORESTS.slice(i, i + chunkSize);
    const { error } = await supabase.from('forests').upsert(chunk, { onConflict: 'id' });
    if (error) { console.error('❌ upsert 실패:', error.message); process.exit(1); }
  }
  console.log(`✅ ${FORESTS.length}개 휴양림 적재 완료`);
  console.log(`   지도 표시 가능(좌표 보유): ${FORESTS.filter((f) => f.geocoded).length}개`);
  console.log('🎉 시드 완료!');
}

run();
